### ISSUE TITLE
Well

### ISSUE THREAD

**Issue by broduer** [FPtje/DarkRPMotd#3]
That is a sad sad day, I hope you got paid well :P

**Comment by FPtje** [comment]
I never got paid for anything DarkRP related, except for a handful of very kind donations. What sad day are you referring to?

**Comment by FPtje** [comment]
If you mean the shutting down of forum and wiki, those were hosted by a company for free. They did so for many years. Sadly those sites required a lot of upkeep, so at a certain point they shut it down. I'm still grateful for all the years they hosted it.

The wiki is now hosted by a free wiki hosting community, and the discord is also managed by other people. While I never earned much with DarkRP, I also never spent much on it.

About the motd, though, maybe it should be updated again.

**Comment by broduer** [comment]
I was mostly referring to the domain, I always thought you had owned the domain and if so I was hoping you got at least was paid over the years for it
Mostly due to the overwhelming traffic the site received throughout the years.
I wasn't trying to insinuate anything, just a friendly, hopeful thought. 

Always have loved this Game mode

#LongLiveDarkRP

**Comment by FPtje** [comment]
Thanks for the kind words! Yeah, gmod and DarkRP have been a great experience for me. Not really financially, but in other ways it's been a wild ride. Crazy things happening, big communities of people coming together, lots of politics, and just lots of plain having fun in a really silly game.

I'm not sure for how long gmod/DarkRP will be played. I'll keep an eye from the sideline, fixing the occasional bug if people can still find them 😉
